-- Schema v1
DO $$ BEGIN CREATE TYPE ticket_status AS ENUM ('UNCLAIMED','CLAIMED','ACTIVE','PENDING_ENTRY','USED','EXPIRED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE mint_status AS ENUM ('PENDING','SUBMITTED','CONFIRMED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,email VARCHAR(255) NOT NULL UNIQUE,sui_address VARCHAR(128),ephemeral_key TEXT,zklogin_proof TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS rides (id BIGSERIAL PRIMARY KEY,ride_id VARCHAR(64) NOT NULL UNIQUE,name VARCHAR(255) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS tickets (id BIGSERIAL PRIMARY KEY,ticket_id VARCHAR(64) NOT NULL UNIQUE,user_id BIGINT REFERENCES users(id),status ticket_status NOT NULL DEFAULT 'UNCLAIMED',purchased_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ticket_vouchers (id BIGSERIAL PRIMARY KEY,voucher_id VARCHAR(64) NOT NULL UNIQUE,purchaser_id BIGINT REFERENCES users(id) NOT NULL,owner_id BIGINT REFERENCES users(id),status ticket_status NOT NULL DEFAULT 'UNCLAIMED',claim_token TEXT,expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS scan_events (id BIGSERIAL PRIMARY KEY,trace_id VARCHAR(64) NOT NULL UNIQUE,user_id BIGINT REFERENCES users(id),ticket_id VARCHAR(64),ride_id VARCHAR(64) NOT NULL,scanned_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_scan_events_user_scanned ON scan_events(user_id,scanned_at);
CREATE INDEX IF NOT EXISTS idx_scan_events_trace ON scan_events(trace_id);
CREATE TABLE IF NOT EXISTS mint_logs (id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) NOT NULL,ride_id VARCHAR(64) NOT NULL,mint_date DATE NOT NULL,tx_digest VARCHAR(128),status mint_status NOT NULL DEFAULT 'PENDING',gas_used BIGINT,error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,ride_id,mint_date));
CREATE INDEX IF NOT EXISTS idx_mint_logs_status ON mint_logs(status);
CREATE INDEX IF NOT EXISTS idx_mint_logs_user_date ON mint_logs(user_id,mint_date);
