DROP TABLE IF EXISTS mint_logs CASCADE;
DROP TABLE IF EXISTS scan_events CASCADE;
DROP TABLE IF EXISTS ticket_vouchers CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS rides CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS mint_status;
DROP TYPE IF EXISTS ticket_status;
